### PR TITLE
Responsive width for youtube embedded player

### PR DESCRIPTION
**Pull request by joaquinmarti**
Quick and dirty css to control youtube iframe size on mobile. Please test it properly before releasing.

### CODE REVIEW

**Comment by gqio** [comment]
This one is tricky.
Did you test it within Astro ?

**Comment by joaquinmarti** [comment]
It's super tricky. I couldn't test it in Astro as I have not the whole environment installed yet. Changes are just css so I don't see any reason to get broken because of Astro.

Now, pushing anything today is a high risk in any case.

**Comment by muryoh** [comment]
I'm gonna push a preview for it

**Comment by muryoh** [comment]
https://dev-designsystems--landing-yt-1c62c9l1.web.app/

**Comment by gqio** [comment]
apparently I cannot have access video control anymore on ios

**Comment by joaquinmarti** [comment]
Must be a z-index issue, I believe. I’ll check it in a while.

**Comment by joaquinmarti** [comment]
Done. Can we redeploy? @muryoh @gqio

**Comment by muryoh** [comment]
On it

**Comment by muryoh** [comment]
https://dev-designsystems--landing-yt-1c62c9l1.web.app

**Comment by muryoh** [comment]
Remember to hard refresh

**Comment by joaquinmarti** [comment]
Thanks a lot, looks better to me now as the video is above the overlay for all resolutions. We should probably test it with a few devices before deciding whether to merge it.

**Comment by muryoh** [comment]
Peek 2021-09-15 12-05

Not great? But better than the previous width issue I guess

**Comment by muryoh** [comment]
Still not centered vertically on mobile when video is active?

**Pull request merged**
