### PR TITLE
fix: add some padding to pricing header for mobile

### PR DESCRIPTION
**Pull request by jorenbroekema**

### CODE REVIEW

**Comment by gqio** [comment]
do you have a screen of what it ffixes ?

**Comment by jorenbroekema** [comment]
Yes,

Before:
image


After:
image

**Comment by gqio** [comment]
Is that what we want maybe too much ? maybe px-4 or px-2  no ?

**Comment by jorenbroekema** [comment]
It may look like a lot because in this scenario it wraps the heading but it can also look like this:
image

Which is almost too little padding in my opinion.
Especially considering we use `px-8` in some other places:
image

**Comment by gqio** [comment]
deal

**Pull request merged**
